## IMPORT PACKAGE

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import sklearn 

# untuk Data Split
from sklearn.model_selection import train_test_split #testing dan training data
# untuk Data Transforming
from sklearn.preprocessing import StandardScaler #standarisasi
from sklearn.preprocessing import MinMaxScaler #normalisasi
# untuk Data Cleaning
from sklearn.impute import SimpleImputer #subtitusi nilai
# untuk Data Encoding
from sklearn.preprocessing import OrdinalEncoder #encoder
from sklearn.preprocessing import OneHotEncoder #onehot

## Record File "Pizza_Restaurants.csv" dan "Datafiniti_Pizza_Restaurants.csv"

In [2]:
df = pd.read_csv('Pizza_Restaurants.csv')
df.head()

id                                  address  \
0  AVwc_6KEIN2L1WUfrKAH  Cascade Village Mall Across From Target   
1  AVwc_6KEIN2L1WUfrKAH  Cascade Village Mall Across From Target   
2  AVwc_6qRByjofQCxkcxw                     148 S Barrington Ave   
3  AVwc_6qRByjofQCxkcxw                     148 S Barrington Ave   
4  AVwc_6qRByjofQCxkcxw                     148 S Barrington Ave   

                       categories         city country  \
0                     Pizza Place         Bend      US   
1                     Pizza Place         Bend      US   
2  American Restaurant,Bar,Bakery  Los Angeles      US   
3  American Restaurant,Bar,Bakery  Los Angeles      US   
4  American Restaurant,Bar,Bakery  Los Angeles      US   

                                                keys   latitude   longitude  \
0  us/or/bend/cascadevillagemallacrossfromtarget/...  44.102665 -121.300797   
1  us/or/bend/cascadevillagemallacrossfromtarget/...  44.102665 -121.300797   
2  us/brentwood/losangeles/148sbarringtonave/-151...  34.064563 -118.469017   
3  us/brentwood/losangeles/148sbarringtonave/-151...  34.064563 -118.469017   
4  us/brentwood/losangeles/148sbarringtonave/-151...  34.064563 -118.469017   

  menuPageURL  menus.amountMax  ...  menus.currency        menus.dateSeen  \
0         NaN            22.50  ...             USD  2016-03-31T02:19:42Z   
1         NaN            18.95  ...             USD  2016-03-31T02:19:42Z   
2         NaN            12.00  ...             USD  2015-10-23T03:57:26Z   
3         NaN            13.00  ...             USD  2015-10-23T03:57:26Z   
4         NaN            13.00  ...             USD  2015-10-23T03:57:26Z   

                  menus.description         menus.name                   name  \
0                               NaN       Bianca Pizza  Little Pizza Paradise   
1                               NaN       Cheese Pizza  Little Pizza Paradise   
2                               NaN  Pizza, Margherita          The Brentwood   
3                               NaN    Pizza, Mushroom          The Brentwood   
4  Olives, onions, capers, tomatoes  Pizza, Puttenesca          The Brentwood   

  postalCode priceRangeCurrency priceRangeMin  priceRangeMax   province  
0      97701                NaN           NaN            NaN         OR  
1      97701                NaN           NaN            NaN         OR  
2      90049                USD          50.0           55.0  Brentwood  
3      90049                USD          50.0           55.0  Brentwood  
4      90049                USD          50.0           55.0  Brentwood  

[5 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3510 entries, 0 to 3509
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  3510 non-null   object 
 1   address             3510 non-null   object 
 2   categories          3510 non-null   object 
 3   city                3510 non-null   object 
 4   country             3510 non-null   object 
 5   keys                3510 non-null   object 
 6   latitude            3510 non-null   float64
 7   longitude           3510 non-null   float64
 8   menuPageURL         610 non-null    object 
 9   menus.amountMax     2948 non-null   float64
 10  menus.amountMin     2948 non-null   float64
 11  menus.currency      2951 non-null   object 
 12  menus.dateSeen      3510 non-null   object 
 13  menus.description   1526 non-null   object 
 14  menus.name          3510 non-null   object 
 15  name                3510 non-null   object 
 16  postal

In [4]:
df2 = pd.read_csv('Datafiniti_Pizza_Restaurants.csv')
df2.head()

id             dateAdded           dateUpdated  \
0  AVz3Y-7h3D1zeR_xDAqm  2017-06-30T05:05:40Z  2019-05-01T15:43:09Z   
1  AVweGPFF_7pvs4fzAAzQ  2016-04-02T04:02:49Z  2019-05-01T15:27:50Z   
2  AVwdRGa9_7pvs4fz4E3K  2016-03-03T18:39:49Z  2019-05-01T12:52:25Z   
3  AVwdX4psIN2L1WUfvJB1  2016-03-29T05:08:59Z  2019-05-01T12:52:20Z   
4  AVwdaeTtkufWRAb55pSH  2016-03-31T02:34:04Z  2019-05-01T12:50:45Z   

             address                                         categories  \
0   4203 E Kiehl Ave  Pizza,Restaurant,American restaurants,Pizza Pl...   
1  25 E Camelback Rd                      Pizza,Pizza Place,Restaurants   
2    3703 Paxton Ave                 Restaurant,Pizza Place,Restaurants   
3    30495 John R Rd       Pizza,Carry-out food,Pizza Place,Restaurants   
4   3600 Eastern Ave  Pizza,American restaurants,Pizza Place,Pizza e...   

               primaryCategories             city country  \
0  Accommodation & Food Services         Sherwood      US   
1  Accommodation & Food Services          Phoenix      US   
2  Accommodation & Food Services       Cincinnati      US   
3  Accommodation & Food Services  Madison Heights      US   
4  Accommodation & Food Services        Baltimore      US   

                                           keys   latitude  ...  \
0      us/ar/sherwood/4203ekiehlave/-1051391616  34.832300  ...   
1       us/az/phoenix/25ecamelbackrd/-727422936  33.509266  ...   
2     us/oh/cincinnati/3703paxtonave/-619797122  39.144883  ...   
3  us/mi/madisonheights/30495johnrrd/-874863116  42.516669  ...   
4    us/md/baltimore/3600easternave/-1270965359  39.286630  ...   

   menus.currency                                     menus.dateSeen  \
0             USD  2018-05-01T04:25:37.197Z,2018-04-16T04:36:02.3...   
1             USD  2018-03-03T02:38:06.381Z,2018-01-18T20:18:10.0...   
2             USD  2018-04-10T07:58:34.585Z,2018-04-21T05:43:21.4...   
3             USD          2016-10-20T21:50:02Z,2016-03-29T05:08:59Z   
4             USD                               2016-03-31T02:34:04Z   

                                   menus.description    menus.name  \
0                                                NaN  Cheese Pizza   
1                                                NaN  Pizza Cookie   
2  a saucelessampcomma double cheese pizza with a...  Pizza Blanca   
3                                                NaN   Small Pizza   
4                                                NaN     Pizza Sub   

                  name postalCode priceRangeCurrency priceRangeMin  \
0   Shotgun Dans Pizza      72120                USD             0   
1     Sauce Pizza Wine      85012                USD             0   
2        Mios Pizzeria      45209                USD             0   
3  Hungry Howies Pizza      48071                USD            25   
4     Spartan Pizzeria      21224                USD             0   

  priceRangeMax province  
0            25       AR  
1            25       AZ  
2            25       OH  
3            40       MI  
4            25       MD  

[5 rows x 24 columns]

In [5]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  10000 non-null  object 
 1   dateAdded           10000 non-null  object 
 2   dateUpdated         10000 non-null  object 
 3   address             10000 non-null  object 
 4   categories          10000 non-null  object 
 5   primaryCategories   10000 non-null  object 
 6   city                10000 non-null  object 
 7   country             10000 non-null  object 
 8   keys                10000 non-null  object 
 9   latitude            10000 non-null  float64
 10  longitude           10000 non-null  float64
 11  menuPageURL         1679 non-null   object 
 12  menus.amountMax     10000 non-null  float64
 13  menus.amountMin     10000 non-null  float64
 14  menus.currency      10000 non-null  object 
 15  menus.dateSeen      10000 non-null  object 
 16  menus

In [6]:
df.isna().sum()

id                       0
address                  0
categories               0
city                     0
country                  0
keys                     0
latitude                 0
longitude                0
menuPageURL           2900
menus.amountMax        562
menus.amountMin        562
menus.currency         559
menus.dateSeen           0
menus.description     1984
menus.name               0
name                     0
postalCode              26
priceRangeCurrency    1953
priceRangeMin         1953
priceRangeMax         1953
province                 0
dtype: int64

In [34]:
df3 = pd.read_csv('dress.csv')
df3.head()

_unit_id   category  category:confidence  \
0  851505458       ikat               0.3487   
1  851505459      plain               1.0000   
2  851505460  polka dot               0.6709   
3  851505461      plain               1.0000   
4  851505462   geometry               0.7035   

                                           image_url  
0  http://s3-eu-west-1.amazonaws.com/we-attribute...  
1  http://s3-eu-west-1.amazonaws.com/we-attribute...  
2  http://s3-eu-west-1.amazonaws.com/we-attribute...  
3  http://s3-eu-west-1.amazonaws.com/we-attribute...  
4  http://s3-eu-west-1.amazonaws.com/we-attribute...

In [35]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15702 entries, 0 to 15701
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   _unit_id             15702 non-null  int64  
 1   category             15702 non-null  object 
 2   category:confidence  15702 non-null  float64
 3   image_url            15702 non-null  object 
dtypes: float64(1), int64(1), object(2)
memory usage: 490.8+ KB


In [7]:
df4 = pd.read_csv('ab_test_2.csv')
df4.head()

user_id    group  views  clicks
0        1  control   10.0     0.0
1        2  control    1.0     0.0
2        3  control    1.0     0.0
3        4  control    2.0     0.0
4        5  control    3.0     0.0

In [8]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   user_id  120000 non-null  int64  
 1   group    120000 non-null  object 
 2   views    120000 non-null  float64
 3   clicks   120000 non-null  float64
dtypes: float64(2), int64(1), object(1)
memory usage: 3.7+ MB


In [9]:
df4.isna().sum()

user_id    0
group      0
views      0
clicks     0
dtype: int64

In [10]:
print(f'panjang dataset {len(df)} baris')

panjang dataset 3510 baris


In [11]:
print(f'panjang dataset {len(df2)} baris')

panjang dataset 10000 baris


## DATA SPLIT 

Train/test split adalah salah satu metode yang dapat digunakan untuk mengevaluasi performa model machine learning. Metode evaluasi model ini membagi dataset menjadi dua bagian yakni bagian yang digunakan untuk training data dan untuk testing data dengan proporsi tertentu.

In [12]:
data = df[['priceRangeCurrency']]
label = df['priceRangeMin']

data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=.3)

In [13]:
print(f'panjang data training {len(data_train)}',
     f'panjang label training {len(label_train)}',
     f'panjang data testing {len(data_test)}',
     f'panjang label testing {len(label_test)}',
     sep='\n')

panjang data training 2457
panjang label training 2457
panjang data testing 1053
panjang label testing 1053


## DATA TRANSFORMASI

Transformasi data adalah merubah skala data kedalam bentuk lain sehingga data memiliki distribusi yang diharapkan.Scaling adalah suatu cara untuk membuat numerical data pada dataset memiliki rentang nilai (scale) yang sama. Tidak ada lagi satu variabel data yang mendominasi variabel data lainnya.Teknik penskalaan yang biasa dipakai yaitu normalisasi dan standardisasi

Normalisasi adalah proses penskalaan data menjadi rentang [0, 1].
Standardisasi adalah proses penskalaan data sehingga memiliki nilai rata-rata 0 dan standar deviasi 1.

In [14]:
dataset_normalisasi = df.copy()
dataset_standarirasi = df4.copy()

NORMALISASI


In [15]:
scaler = MinMaxScaler()

normalize_dataset = scaler.fit_transform(dataset_normalisasi[['priceRangeMin', 'priceRangeMax',]])

normalize_dataset = pd.DataFrame(normalize_dataset)
normalize_dataset.rename(columns={ 0 :'priceRangeMin', 1 : 'priceRangeMax',}, inplace=True)

normalize_dataset.head(5)

priceRangeMin  priceRangeMax
0            NaN            NaN
1            NaN            NaN
2       0.144092       0.065749
3       0.144092       0.065749
4       0.144092       0.065749

In [16]:
dataset_standarirasi.drop('group', axis=1, inplace=True)

standart_std = StandardScaler()

scaled_data = standart_std.fit_transform(dataset_standarirasi)

print('Dataset sebelum scalling:',  # SEBELUM
      df4.drop('group', axis=1).head(6),
      f'Nilai standar deviasi:\n{np.std(df4)}',
      sep='\n', end='\n\n')

print('Dataset setelah scalling:',  # SESUDAH
      scaled_data[:6],
      f'Nilai standar deviasi: {np.std(scaled_data)}',
      sep='\n')

Dataset sebelum scalling:
   user_id  views  clicks
0        1   10.0     0.0
1        2    1.0     0.0
2        3    1.0     0.0
3        4    2.0     0.0
4        5    3.0     0.0
5        6    4.0     1.0
Nilai standar deviasi:
user_id    34641.016150
views          5.915175
clicks         0.472545
dtype: float64

Dataset setelah scalling:
[[-1.73203637  0.84679236 -0.38661223]
 [-1.73200751 -0.67471799 -0.38661223]
 [-1.73197864 -0.67471799 -0.38661223]
 [-1.73194977 -0.50566129 -0.38661223]
 [-1.7319209  -0.33660458 -0.38661223]
 [-1.73189204 -0.16754787  1.72958845]]
Nilai standar deviasi: 0.9999999999999999


c:\users\aspire 5\appdata\local\programs\python\python39\lib\site-packages\numpy\core\fromnumeric.py:3571: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


## DATA CLEANING

Data yang kita gunakan bisa jadi sangat berantakan. Ada informasi yang tak lengkap, ada pula format yang berbeda-beda.Semua ini tentu membuat data itu sulit diolah. Pada akhirnya, ia jadi tak bisa dimanfaatkan. Untuk itulah kita harus melakukan data cleaning terlebih dahulu. Data cleaning adalah memperbarui, membetulkan, dan membuat data menjadi lebih rapi. Beberapa model machine learning tidak dapat bekerja dengan data yang masih berantakan. Kesalahan dalam data dapat berupa:

Terdapat nilai data yang tidak valid (Null)
Data dalam format yang salah
Terdapat duplikat

In [17]:
dataset_ns = df4.copy()
dataset_ns2 = df2.copy()
dataset_ns3 = df.copy()

In [18]:
imputer_mean = SimpleImputer(strategy='mean')
imputer_median = SimpleImputer(strategy='median')
imputer_modus = SimpleImputer(strategy='most_frequent')

MODUS

In [19]:
dataset_ns['group'] = imputer_modus.fit_transform(dataset_ns[['group']])

dataset_ns.isna().sum()

user_id    0
group      0
views      0
clicks     0
dtype: int64

MEAN

In [23]:
#dataset_ns2['user_id'] = imputer_mean.fit_transform(dataset_ns2[['user_id']])

#dataset_ns2.isna().sum()

MENGHAPUS RECORF/FEATURE

In [24]:
dataset_ns3.dropna(inplace=True)

dataset_ns3.isna().sum()

id                    0
address               0
categories            0
city                  0
country               0
keys                  0
latitude              0
longitude             0
menuPageURL           0
menus.amountMax       0
menus.amountMin       0
menus.currency        0
menus.dateSeen        0
menus.description     0
menus.name            0
name                  0
postalCode            0
priceRangeCurrency    0
priceRangeMin         0
priceRangeMax         0
province              0
dtype: int64

In [25]:
len(dataset_ns)

120000

DATA DUPLIKAT

In [36]:
dataset_duplicate = df3.copy()

dataset_duplicate.duplicated().sum()

0

## ENCODING

Encoding adalah salah tahap pre-processing ketika kita menghadapi data yang bersifat kategorikal. Encoding adalah teknik yang mengubah variabel kategorikal menjadi variabel numerik, model dalam machine learning membutuhkan input yang bertipe numerik sehingga sangat penting bagi kita untuk melakukan encoding jika terdapat variabel yang bertipe kategorikal didalam data kita. Teknik encoding yang paling terkenal adalah Ordinal Encoding dan One-Hot Encoding

In [39]:
dataset_ordinal = df3.copy()
dataset_one_hot = df3.copy()

In [41]:
df3['category'].unique()

array(['ikat', 'plain', 'polka dot', 'geometry', 'floral', 'squares',
       'scales', 'animal', 'OTHER', 'stripes', 'tribal', 'houndstooth',
       'cartoon', 'chevron', 'stars', 'letter_numb', 'skull'],
      dtype=object)

ORDINAL

In [43]:
encoder_ordinal =OrdinalEncoder()

#encoding kan
dataset_ordinal['category'] = encoder_ordinal.fit_transform(dataset_ordinal[['category']]).astype('int64')

#lihat
dataset_ordinal.head()

_unit_id  category  category:confidence  \
0  851505458         7               0.3487   
1  851505459         9               1.0000   
2  851505460        10               0.6709   
3  851505461         9               1.0000   
4  851505462         5               0.7035   

                                           image_url  
0  http://s3-eu-west-1.amazonaws.com/we-attribute...  
1  http://s3-eu-west-1.amazonaws.com/we-attribute...  
2  http://s3-eu-west-1.amazonaws.com/we-attribute...  
3  http://s3-eu-west-1.amazonaws.com/we-attribute...  
4  http://s3-eu-west-1.amazonaws.com/we-attribute...

In [44]:
dataset_ordinal['category'].unique()

array([ 7,  9, 10,  5,  4, 13, 11,  1,  0, 15, 16,  6,  2,  3, 14,  8, 12],
      dtype=int64)

ONE-HOT

In [45]:
temp_dataset = pd.get_dummies(dataset_one_hot[['category']])

temp_dataset = pd.DataFrame(temp_dataset)

dataset_one_hot.drop('category', axis=1, inplace=True)

dataset_one_hot = dataset_one_hot.join(temp_dataset)
dataset_one_hot.head(5)

_unit_id  category:confidence  \
0  851505458               0.3487   
1  851505459               1.0000   
2  851505460               0.6709   
3  851505461               1.0000   
4  851505462               0.7035   

                                           image_url  category_OTHER  \
0  http://s3-eu-west-1.amazonaws.com/we-attribute...               0   
1  http://s3-eu-west-1.amazonaws.com/we-attribute...               0   
2  http://s3-eu-west-1.amazonaws.com/we-attribute...               0   
3  http://s3-eu-west-1.amazonaws.com/we-attribute...               0   
4  http://s3-eu-west-1.amazonaws.com/we-attribute...               0   

   category_animal  category_cartoon  category_chevron  category_floral  \
0                0                 0                 0                0   
1                0                 0                 0                0   
2                0                 0                 0                0   
3                0                 0                 0                0   
4                0                 0                 0                0   

   category_geometry  category_houndstooth  category_ikat  \
0                  0                     0              1   
1                  0                     0              0   
2                  0                     0              0   
3                  0                     0              0   
4                  1                     0              0   

   category_letter_numb  category_plain  category_polka dot  category_scales  \
0                     0               0                   0                0   
1                     0               1                   0                0   
2                     0               0                   1                0   
3                     0               1                   0                0   
4                     0               0                   0                0   

   category_skull  category_squares  category_stars  category_stripes  \
0               0                 0               0                 0   
1               0                 0               0                 0   
2               0                 0               0                 0   
3               0                 0               0                 0   
4               0                 0               0                 0   

   category_tribal  
0                0  
1                0  
2                0  
3                0  
4                0