## IMPORT PACKAGE 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

## 1. CONSTANT TENSOR

### a. tf.constant()

In [2]:
#membuat sebuah nilai constant tensor menggunakan tensorflow
const_d = tf.constant ([[1,2,3,4,5],[2,9,8,3,4],
                       [2,5,1,4,3],[7,6,8,5,1],
                       [4,5,6,7,8]], shape= [5,5], dtype = tf.float64)
#Print nilai constant tensor yang dibuat sebelumnya
const_d

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[1., 2., 3., 4., 5.],
       [2., 9., 8., 3., 4.],
       [2., 5., 1., 4., 3.],
       [7., 6., 8., 5., 1.],
       [4., 5., 6., 7., 8.]])>

### b. tf.zeros()

In [3]:
#Penggunaan tf.zeros
zero_d = tf.zeros(shape=[2,3,5,5])

#Pengecekan Nilai constant 
zero_d

<tf.Tensor: shape=(2, 3, 5, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], d

### c. tf.fill()

In [4]:
#pengguanaan tf.fill
fill_d = tf.fill([5,5],2)

#Pengecekan nilai cosntant
fill_d

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])>

### d.  tf.random()

In [5]:
#Penggunaan tf.random.normal()
random_d = tf.random.normal([5,5], mean=1)

random_d

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.01306885,  1.3685699 ,  1.215642  ,  2.0892253 ,  1.1469986 ],
       [-0.8361368 ,  1.0463417 ,  1.7475781 , -1.0336571 ,  1.0612867 ],
       [ 1.1274445 ,  0.2521782 ,  0.8713475 ,  1.9278045 ,  1.7747588 ],
       [ 1.7029523 ,  1.2695292 ,  0.9805882 ,  1.1281898 ,  1.6904486 ],
       [ 3.3649325 ,  0.8277124 ,  1.541867  ,  0.10560149, -1.0061011 ]],
      dtype=float32)>

### e. tf.convert_to_tensor

In [6]:
#Pembuataan list untuk dimasukan kedalam sebuah tensor 
list_d = [1,2,3,4,5,6]

#Penggunaan tf.convert_to_tensor
convert_d = tf.convert_to_tensor(list_d,)

convert_d

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

## 2. VARIABLE TENSOR

In [7]:
var_D = tf.Variable(tf.ones([5,5]))
var_D

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [8]:
#
print("Value of the variable var_1:", var_D.read_value())

Value of the variable var_1: tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)


In [9]:
var_value_1= [[3,4,8,9,7], [11,12,3,4,5],[2,5,3,4,8],[3,7,8,4,5],
             [2,1,6,4,2]]
var_D.assign(var_value_1)
print("Value of the variable var_1: after the assignment:", var_D.read_value())

Value of the variable var_1: after the assignment: tf.Tensor(
[[ 3.  4.  8.  9.  7.]
 [11. 12.  3.  4.  5.]
 [ 2.  5.  3.  4.  8.]
 [ 3.  7.  8.  4.  5.]
 [ 2.  1.  6.  4.  2.]], shape=(5, 5), dtype=float32)


In [10]:
var_value_1=[[1,2,3,4,5], [4,5,6,8,7], [12,13,14,11,15],
            [3,8,5,7,9], [4,5,9,10,11]]
var_D.assign_add(var_value_1)
var_D

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[ 4.,  6., 11., 13., 12.],
       [15., 17.,  9., 12., 12.],
       [14., 18., 17., 15., 23.],
       [ 6., 15., 13., 11., 14.],
       [ 6.,  6., 15., 14., 13.]], dtype=float32)>

## Tensor Slicing and Indexing

### 1. Slicing

In [11]:
tensor_i = tf.random.normal([4,3,6,7,9])
tensor_i

<tf.Tensor: shape=(4, 3, 6, 7, 9), dtype=float32, numpy=
array([[[[[ 1.13416326e+00, -1.40693498e+00, -3.12496990e-01, ...,
           -2.18018025e-01, -1.57174516e+00, -8.34952742e-02],
          [-1.20869839e+00, -1.08874655e+00,  8.47688079e-01, ...,
            4.68013048e-01, -2.38922334e+00,  1.43478012e+00],
          [ 2.08902144e+00, -5.40685833e-01, -1.08109009e+00, ...,
            9.88424301e-01, -1.83317828e+00, -7.16705680e-01],
          ...,
          [ 3.79643023e-01, -4.19065744e-01, -1.50687713e-02, ...,
            1.42343491e-01,  6.86299026e-01,  1.61578655e+00],
          [-6.48729503e-01,  2.33619928e+00, -6.09880626e-01, ...,
            1.62235034e+00, -2.56292850e-01,  7.14842975e-02],
          [ 1.17887330e+00, -1.08456123e+00, -7.71753967e-01, ...,
           -5.23626387e-01, -3.31274092e-01, -4.21249270e-01]],

         [[-1.11733699e+00, -6.97501421e-01, -5.33261836e-01, ...,
           -2.42941573e-01,  6.57482564e-01, -6.32003129e-01],
          [ 1.30

In [12]:
tensor_i[0,:,:,:]

<tf.Tensor: shape=(3, 6, 7, 9), dtype=float32, numpy=
array([[[[ 1.13416326e+00, -1.40693498e+00, -3.12496990e-01, ...,
          -2.18018025e-01, -1.57174516e+00, -8.34952742e-02],
         [-1.20869839e+00, -1.08874655e+00,  8.47688079e-01, ...,
           4.68013048e-01, -2.38922334e+00,  1.43478012e+00],
         [ 2.08902144e+00, -5.40685833e-01, -1.08109009e+00, ...,
           9.88424301e-01, -1.83317828e+00, -7.16705680e-01],
         ...,
         [ 3.79643023e-01, -4.19065744e-01, -1.50687713e-02, ...,
           1.42343491e-01,  6.86299026e-01,  1.61578655e+00],
         [-6.48729503e-01,  2.33619928e+00, -6.09880626e-01, ...,
           1.62235034e+00, -2.56292850e-01,  7.14842975e-02],
         [ 1.17887330e+00, -1.08456123e+00, -7.71753967e-01, ...,
          -5.23626387e-01, -3.31274092e-01, -4.21249270e-01]],

        [[-1.11733699e+00, -6.97501421e-01, -5.33261836e-01, ...,
          -2.42941573e-01,  6.57482564e-01, -6.32003129e-01],
         [ 1.30438483e+00,  6.9499

In [13]:
tensor_i[1,...]

<tf.Tensor: shape=(3, 6, 7, 9), dtype=float32, numpy=
array([[[[-9.70131233e-02, -1.23879504e+00, -1.88408577e+00, ...,
           9.20704186e-01,  6.73621535e-01,  8.66435587e-01],
         [ 2.34166294e-01,  1.46238923e+00, -5.73601723e-01, ...,
          -2.47627330e+00,  2.04146242e+00,  1.73443615e-01],
         [-1.12867117e+00, -5.52454114e-01,  1.05715609e+00, ...,
           6.44633114e-01,  2.11569697e-01, -4.74119425e-01],
         ...,
         [-8.37931558e-02,  1.15548754e+00,  3.08232880e+00, ...,
          -1.39697552e+00, -2.81363457e-01, -1.46547019e-01],
         [-1.11479199e+00, -6.13611281e-01,  9.24141765e-01, ...,
          -2.73334193e+00,  2.55220628e+00,  7.17701077e-01],
         [-2.06475949e+00, -1.31264019e+00, -7.67238081e-01, ...,
           2.59726018e-01,  1.07625658e-02, -1.58691025e+00]],

        [[ 6.78221881e-01, -1.73332021e-01,  9.36588049e-01, ...,
          -1.08453906e+00, -1.85381162e+00,  5.15220225e-01],
         [-4.06654226e-03, -8.5083

In [14]:
tensor_i[::-1,...]

<tf.Tensor: shape=(4, 3, 6, 7, 9), dtype=float32, numpy=
array([[[[[-2.65058041e-01, -1.47389829e+00,  2.37035021e-01, ...,
            1.62155300e-01, -1.01427741e-01,  1.11488593e+00],
          [ 5.15060604e-01, -2.29265738e+00, -4.91482884e-01, ...,
            6.17921770e-01, -3.63444269e-01, -3.09651881e-01],
          [ 5.76137304e-01, -1.10054694e-01,  1.02236021e+00, ...,
            9.23162922e-02, -2.19454169e-01,  2.45943055e-01],
          ...,
          [ 2.27040839e+00,  3.87732014e-02,  9.47645545e-01, ...,
           -4.18759227e-01, -2.01993942e+00,  3.64047587e-01],
          [-3.75440776e-01, -1.31642640e+00, -6.99294746e-01, ...,
           -2.77393181e-02, -1.32480145e+00, -7.44795382e-01],
          [ 1.61226487e+00,  1.64110041e+00,  7.23585427e-01, ...,
            6.79740191e-01, -2.68028736e+00,  6.28977656e-01]],

         [[-7.38849103e-01, -1.36206901e+00,  3.86899650e-01, ...,
           -6.40446603e-01, -1.12316959e-01,  1.31440067e+00],
          [-8.64

### 2. Indexing

### a. tf.gather()

In [15]:
index = [1]
tf.gather(tensor_i, indices=index)

<tf.Tensor: shape=(1, 3, 6, 7, 9), dtype=float32, numpy=
array([[[[[-9.70131233e-02, -1.23879504e+00, -1.88408577e+00, ...,
            9.20704186e-01,  6.73621535e-01,  8.66435587e-01],
          [ 2.34166294e-01,  1.46238923e+00, -5.73601723e-01, ...,
           -2.47627330e+00,  2.04146242e+00,  1.73443615e-01],
          [-1.12867117e+00, -5.52454114e-01,  1.05715609e+00, ...,
            6.44633114e-01,  2.11569697e-01, -4.74119425e-01],
          ...,
          [-8.37931558e-02,  1.15548754e+00,  3.08232880e+00, ...,
           -1.39697552e+00, -2.81363457e-01, -1.46547019e-01],
          [-1.11479199e+00, -6.13611281e-01,  9.24141765e-01, ...,
           -2.73334193e+00,  2.55220628e+00,  7.17701077e-01],
          [-2.06475949e+00, -1.31264019e+00, -7.67238081e-01, ...,
            2.59726018e-01,  1.07625658e-02, -1.58691025e+00]],

         [[ 6.78221881e-01, -1.73332021e-01,  9.36588049e-01, ...,
           -1.08453906e+00, -1.85381162e+00,  5.15220225e-01],
          [-4.06

### b. tf.gather_nd

In [16]:
index = [[0,2,],[1,1],[1,2],[0,1],[2,2]]
tf.gather_nd(tensor_i,indices=index)

<tf.Tensor: shape=(5, 6, 7, 9), dtype=float32, numpy=
array([[[[-7.08168864e-01,  4.77955848e-01, -1.53853631e+00, ...,
           1.12730905e-01,  7.96070635e-01,  8.05399179e-01],
         [-6.39100373e-01,  6.50877595e-01,  1.26787677e-01, ...,
           6.44417405e-01,  7.99238563e-01, -2.87133455e-01],
         [-1.24725759e+00, -8.81245494e-01,  7.49221265e-01, ...,
           1.28936749e-02,  7.61785865e-01,  1.67500699e+00],
         ...,
         [ 6.61309898e-01,  1.23230839e+00, -6.41617537e-01, ...,
          -7.64407218e-01,  1.05617023e+00, -1.29142749e+00],
         [ 5.72565019e-01,  1.07804202e-01, -9.28485453e-01, ...,
           1.87434387e+00, -2.77762324e-01,  1.00938685e-01],
         [-1.71925053e-01,  1.23231399e+00, -5.63385010e-01, ...,
           2.27914765e-01, -1.71804225e+00,  7.46067047e-01]],

        [[ 3.45457286e-01,  6.23551130e-01, -1.49887788e+00, ...,
           7.78650939e-01, -1.75727379e+00,  1.02261686e+00],
         [-2.37485602e-01, -4.6715

## TENSOR DIMENSION MODIFICATION

### 1. Dimension Display

In [17]:
const_2E = tf.constant([[1,2,3,4,5], [4,5,6,8,7], [12,13,14,11,15],
            [3,8,5,7,9], [4,5,9,10,11]], shape = [5,5])
const_2E

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  8,  7],
       [12, 13, 14, 11, 15],
       [ 3,  8,  5,  7,  9],
       [ 4,  5,  9, 10, 11]])>

In [18]:
const_2E.shape

TensorShape([5, 5])

In [19]:
tf.shape(const_2E)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

### 2. Dimension Reshaping

In [20]:
const_E =tf.constant([[1,2,3,5,7],[4,5,6,4,7],[17,12,15,16,8]])
const_E


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  5,  7],
       [ 4,  5,  6,  4,  7],
       [17, 12, 15, 16,  8]])>

In [21]:
tf.reshape(const_E, (5,3))

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 5,  7,  4],
       [ 5,  6,  4],
       [ 7, 17, 12],
       [15, 16,  8]])>

### 3. Dimension Expanding

In [22]:
tensor_e = tf.random.normal([5,5], mean=5)
tensor_e.shape

TensorShape([5, 5])

In [23]:
tensor_exp_e = tf.random.normal([2,3,4,9,6], mean=5)
tensor_exp_e.shape

TensorShape([2, 3, 4, 9, 6])

In [24]:
tf.expand_dims(tensor_e, axis=2).shape

TensorShape([5, 5, 1])

In [25]:
tensor_b = tf.expand_dims(tensor_exp_e, axis=1)
tensor_b.shape

TensorShape([2, 1, 3, 4, 9, 6])

### 4. Dimension Squeese

In [26]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
squeeze_sample_1 = tf.random.normal([2,100,100,4])
print("size of the original data:",squeeze_sample_1.shape)

size of the original data: (2, 100, 100, 4)


### 5. Transpose

In [27]:
const_d = tf.constant([[1,2,3,4,5],[2,9,8,3,4],
                       [2,5,1,4,3],[7,6,8,5,1],
                       [4,5,6,7,8]], shape=[5,5])
const_d

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 5],
       [2, 9, 8, 3, 4],
       [2, 5, 1, 4, 3],
       [7, 6, 8, 5, 1],
       [4, 5, 6, 7, 8]])>

tf.transpose(const_d)

### 6. Broadcast

In [28]:
tf.broadcast_to(const_d, shape=[5,5])

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 5],
       [2, 9, 8, 3, 4],
       [2, 5, 1, 4, 3],
       [7, 6, 8, 5, 1],
       [4, 5, 6, 7, 8]])>

In [29]:
d = tf.constant([[1,2,3],[5,2,9], [4,5,6]])
e = tf.constant([[7,8,9], [1,2,3], [10,8,9]])

tf.pow(d,e)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[       1,      256,    19683],
       [       5,        4,      729],
       [ 1048576,   390625, 10077696]])>

## Arithmetic Operations on Tensors

### 1. Arithmetic Operator

dimana berisikan sebuah perhitungan arimatika sebuah tensorflow yang ada sekitar 6 opersi aritmetika. yaitu tf.add(), tf.subtraction(), tf.multiply() perkalian tf.divide() pembagian, tf.math.log()logaritma, tf.pow() pangkat

In [30]:
#aritmetika tf.add()
d = tf.constant([[3,5,6,3,1],[4,8,2,6,4],[10,5,2,3,1],
                 [7,6,2,9,2],[5,6,3,4,5]])
e = tf.constant([[1,6,8,9,2],[2,9,5,6,7],[1,2,8,3,6],
                 [2,1,8,9,5],[6,9,10,11,3]])

print("Hasil dari Penjumlahan adalah:\n",tf.add(d, e))

Hasil dari Penjumlahan adalah:
 tf.Tensor(
[[ 4 11 14 12  3]
 [ 6 17  7 12 11]
 [11  7 10  6  7]
 [ 9  7 10 18  7]
 [11 15 13 15  8]], shape=(5, 5), dtype=int32)


In [31]:
#aritmatika tf.multiply()
d = tf.constant([[3,5,6,3,1],[4,8,2,6,4],[10,5,2,3,1],
                 [7,6,2,9,2],[5,6,3,4,5]])
e = tf.constant([[1,6,8,9,2],[2,9,5,6,7],[1,2,8,3,6],
                 [2,1,8,9,5],[6,9,10,11,3]])

print("Hasil dari Perkalian adalah:\n",tf.multiply(d, e))

Hasil dari Perkalian adalah:
 tf.Tensor(
[[ 3 30 48 27  2]
 [ 8 72 10 36 28]
 [10 10 16  9  6]
 [14  6 16 81 10]
 [30 54 30 44 15]], shape=(5, 5), dtype=int32)


In [32]:
#aritmatika tf.divide()
d = tf.constant([[3,5,6,3,1],[4,8,2,6,4],[10,5,2,3,1],
                 [7,6,2,9,2],[5,6,3,4,5]])
e = tf.constant([[1,6,8,9,2],[2,9,5,6,7],[1,2,8,3,6],
                 [2,1,8,9,5],[6,9,10,11,3]])

print("Hasil dari Pembagian adalah:\n",tf.divide(d, e))

Hasil dari Pembagian adalah:
 tf.Tensor(
[[ 3.          0.83333333  0.75        0.33333333  0.5       ]
 [ 2.          0.88888889  0.4         1.          0.57142857]
 [10.          2.5         0.25        1.          0.16666667]
 [ 3.5         6.          0.25        1.          0.4       ]
 [ 0.83333333  0.66666667  0.3         0.36363636  1.66666667]], shape=(5, 5), dtype=float64)


In [33]:
#aritmatika tf.pow()
d = tf.constant([[3,5,6,3,1],[4,8,2,6,4],[10,5,2,3,1],
                 [7,6,2,9,2],[5,6,3,4,5]])
e = tf.constant([[1,6,8,9,2],[2,9,5,6,7],[1,2,8,3,6],
                 [2,1,8,9,5],[6,9,10,11,3]])

print("Hasil dari Pangkat adalah:\n",tf.pow(d, e))

Hasil dari Pangkat adalah:
 tf.Tensor(
[[        3     15625   1679616     19683         1]
 [       16 134217728        32     46656     16384]
 [       10        25       256        27         1]
 [       49         6       256 387420489        32]
 [    15625  10077696     59049   4194304       125]], shape=(5, 5), dtype=int32)


In [34]:
# #aritmatika tf.subtraction()
# d = tf.constant([[3,5,6,3,1],[4,8,2,6,4],[10,5,2,3,1],
#                  [7,6,2,9,2],[5,6,3,4,5]])
# e = tf.constant([[1,6,8,9,2],[2,9,5,6,7],[1,2,8,3,6],
#                  [2,1,8,9,5],[6,9,10,11,3]])

# print("Hasil dari Pengurangan adalah:\n",tf.subtraction(d,e))

### 2. Matrix Multiplication

Matrix Multiplication diterapkan dengan memanggil tf.matmul()

In [35]:
tf.matmul(d, e)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 31,  87, 131, 113,  95],
       [ 58, 142, 176, 188, 118],
       [ 34, 121, 155, 164,  85],
       [ 51, 127, 194, 208, 119],
       [ 58, 139, 176, 181, 105]])>

### 3. Tensor Statistics Collection

Metode untuk mengambil statistik dari tensor menggunakan
tf.argmax()/tf.argmin() digunakan untuk mengalkulasi posisi nilai maksimum
atau minimum

In [36]:
argmax_sample_1 = tf.constant([[1,2,3,4,5],[2,9,8,3,4],
                       [2,5,1,4,3],[7,6,8,5,1],
                       [4,5,6,7,8]])
print("input tensor:",argmax_sample_1.numpy())

input tensor: [[1 2 3 4 5]
 [2 9 8 3 4]
 [2 5 1 4 3]
 [7 6 8 5 1]
 [4 5 6 7 8]]


In [37]:
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
print("locate the maximum value by column:",max_sample_1.numpy())

locate the maximum value by column: [3 1 1 4 4]


In [38]:
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("locate the maximum value by row:",max_sample_2.numpy())

locate the maximum value by row: [4 1 1 2 4]


In [39]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data",reduce_sample_1.numpy())

original data [[1 2 3]
 [4 5 6]]


## Tensor Concatenation and SPlitting

### 1. Tensor Concatenation

#### A. tf.contact()

In [40]:
concat_sample_1 = tf.random.normal([5,100,100,4])
concat_sample_2 = tf.random.normal([50,100,100,4])

print("sizes of the original data:",concat_sample_1.shape,concat_sample_2.shape)

sizes of the original data: (5, 100, 100, 4) (50, 100, 100, 4)


In [41]:
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("size of the concatenated data:",concated_sample_1.shape)

size of the concatenated data: (55, 100, 100, 4)


#### B. tf.stack()

In [42]:
stack_sample_1 = tf.random.normal([1000,1000,50])
stack_sample_2 = tf.random.normal([1000,1000,50])

print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)

sizes of the original data:  (1000, 1000, 50) (1000, 1000, 50)


In [43]:
#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

size of the concatenated data: (2, 1000, 1000, 50)


### 2. Tensor Splitting

#### A. tf.unstack()

In [44]:
arr_random1 = tf.random.normal((3,3,3), seed=1)

In [45]:
#split
arr_random_1_1= tf.concat([arr_random1], axis=0)

In [46]:
arr_random_1_2= tf.stack([arr_random1], axis=0)

In [47]:
temp= tf.split(arr_random_1_1, num_or_size_splits=3)
temp

[<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
 array([[[-0.8113182 ,  1.4845988 ,  0.06532937],
         [-2.4427042 ,  0.0992484 ,  0.5912243 ],
         [ 0.59282297, -2.1229296 , -0.72289723]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
 array([[[-0.05627038,  0.6435448 , -0.26432407],
         [ 1.8566332 ,  0.5678417 , -0.3828359 ],
         [-1.4853433 ,  1.2617711 , -0.02530608]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
 array([[[-0.2646297 ,  1.5328138 , -1.7429771 ],
         [-0.43789294, -0.56601   ,  0.32066926],
         [ 1.132831  , -2.2782571 ,  0.48281202]]], dtype=float32)>]

In [48]:
temp, temp1, temp2,= tf.split(arr_random_1_1, num_or_size_splits=3)
temp2

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[-0.2646297 ,  1.5328138 , -1.7429771 ],
        [-0.43789294, -0.56601   ,  0.32066926],
        [ 1.132831  , -2.2782571 ,  0.48281202]]], dtype=float32)>

In [52]:
#Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(1000, 1000, 50), dtype=float32, numpy=
 array([[[ 1.42320502e+00, -2.35110259e+00, -1.61933434e+00, ...,
          -2.90499091e-01, -1.65204847e+00, -1.49829662e+00],
         [ 4.85310018e-01, -1.11023653e+00, -1.30658579e+00, ...,
           7.41384745e-01,  1.02580142e+00,  1.98809803e-02],
         [ 1.21780455e+00,  1.20648646e+00, -1.84478268e-01, ...,
          -1.35853851e+00,  3.54994833e-01,  4.47648704e-01],
         ...,
         [ 4.56390947e-01, -8.89544860e-02, -1.04187131e+00, ...,
           5.97739279e-01, -5.93341608e-03,  1.89924568e-01],
         [ 1.01271605e+00, -9.19216037e-01,  2.50604838e-01, ...,
           2.60734469e-01, -6.19748175e-01, -1.09010017e+00],
         [ 4.03507710e-01, -2.44511038e-01, -7.74047911e-01, ...,
           8.09069499e-02, -1.62994102e-01,  2.44364426e-01]],
 
        [[-7.59332478e-01,  7.52906561e-01,  3.15711424e-02, ...,
           1.31881595e+00, -3.56409967e-01,  1.05998600e+00],
         [-6.30255401e-01,  

In [58]:

split_sample_1 = tf.random.normal([1000,1000,50])
print("size of the original data:",split_sample_1.shape)
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)
print("size of the split data when m_or_size_splits is set to 5:",np.shape(splited_sample_1))


size of the original data: (1000, 1000, 50)
size of the split data when m_or_size_splits is set to 5: (5, 200, 1000, 50)


## Tensor Sorting Methods

### 1. tf.sort() & tf.argsort()

In [60]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())

input tensor: [0 3 6 9 4 2 8 5 1 7]


In [62]:
sorted_sample_1 = tf.sort(sort_sample_1, direction="DESCENDING")
print("tensor sorted in descending order:",sorted_sample_1.numpy())

tensor sorted in descending order: [9 8 7 6 5 4 3 2 1 0]


In [63]:
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())

tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]


In [64]:
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

indexes of elements in ascending order: [0 8 5 1 4 7 2 9 6 3]


In [65]:
sorted_sample_2 = tf.argsort(sort_sample_1,direction="DESCENDING")
print("indexes of elements in descending order:",sorted_sample_2.numpy())

indexes of elements in descending order: [3 6 9 2 7 4 1 5 8 0]


In [66]:
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

indexes of elements in ascending order: [0 8 5 1 4 7 2 9 6 3]


### 2. tf.nn.tpp_k()

In [67]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor:",sort_sample_1.numpy())

input tensor: [0 3 6 9 4 2 8 5 1 7]


In [68]:
print("first five values in ascending order:", values.numpy())

first five values in ascending order: [9 8 7 6 5]


In [69]:
print("indexes of the first five values in ascending order:", index.numpy())

indexes of the first five values in ascending order: [3 6 9 2 7]


In [70]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

a = tf.ones((2, 2), dtype=tf.dtypes.float32)
b = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
c = tf.matmul(a, b)

with tf.Session() as sess:
    print(sess.run(c))

[[4. 6.]
 [4. 6.]]


In [71]:
import timeit

cnn_cell = tf.keras.layers.Conv2D(filters=200, kernel_size=2, strides=(1,1))

In [72]:
@tf.function
def cnn_fn(image):
    return cnn_cell(image)

In [73]:
image = tf.zeros([100,100,100,10])

In [74]:
cnn_cell(image)
cnn_fn(image) 

<tf.Tensor 'StatefulPartitionedCall:0' shape=(100, 99, 99, 200) dtype=float32>

In [75]:
print(timeit.timeit(lambda: cnn_cell(image), number=10))
print(timeit.timeit(lambda: cnn_fn(image), number=10))

0.02213500000004842
0.010616300000037882
